//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CarDealer.EF
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblcar
    {
        public int Id { get; set; }
        public string CarPrice { get; set; }
        public string OfferPrice { get; set; }
        public string City { get; set; }
        public string Make { get; set; }
        public string Model { get; set; }
        public Nullable<System.DateTime> FirstRegistration { get; set; }
        public string Mileage { get; set; }
        public string Fuel { get; set; }
        public string EngineSize { get; set; }
        public string Power { get; set; }
        public string GearBox { get; set; }
        public Nullable<int> NumberOfSeat { get; set; }
        public Nullable<int> Doors { get; set; }
        public string Color { get; set; }
        public string Description { get; set; }
        public string Extra { get; set; }
        public string Image { get; set; }
    }
}
